### ISSUE TITLE
[Bug] Explosions causing disconnect on servers

### ISSUE THREAD

**Issue by alfredggttv** [Xylonity/Explosive-Enhancement-Reforged#1]
Devs much smarter than I am have figured out that a certain particle from the mod can cause a disconnect.

You can find the details here: https://github.com/iron431/irons-spells-n-spellbooks/issues/643#issuecomment-2438449315

Log: https://gist.github.com/alfredggttv/d5288a5d16968570333861aa3252952c

Bug happening: https://www.twitch.tv/ftb/clip/SparklingCourageousShrewThunBeast-ZzzkLmCpxcialyfU

Mod Version: explosiveenhancement-1.0.1
Neoforge 21.1.71
MC Version 1.21.1

**Comment by Xylonity** [comment]
Thank you for informing me. I will fix the issue in the next few days, as soon as I am able.
