### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by VaporeonScripts** [Xylonity/Explosive-Enhancement-Reforged#2]
https://mclo.gs/5HDqpt5

**Comment by VaporeonScripts** [comment]
With iron spells books boss,hope this helps
1.21.1 neoforge .73

**Comment by Xylonity** [comment]
I'll fix that as soon as I'm available

**Comment by Xylonity** [comment]
What modpack are you playing on? I can test directly by myself :)

**Comment by VaporeonScripts** [comment]
NeoTech reborn

**Comment by VaporeonScripts** [comment]
Seems like the when some attacks are triggered it crashes,defo Chz triggers the explosion which should be changed to the enhanced one

**Comment by Xylonity** [comment]
I'll test this as soon as I can. Try disabling the mod lithium?
